#!/bin/bash

source creep/runes/runes.sh
source creep/creep.sh

runes.load
runes.decrypt.start

# Reading the files changed in last commit
FILES=$(git.changes)

for FILE in ${FILES[@]}; do
	FILE=${FILE#*  } # Trimming that leading "M  " status marker.

	if runes.isRune $FILE; then
		runes.decrypt $FILE
	fi;
done
