#!/bin/bash

source creep/runes/runes.sh
source creep/creep.sh

runes.load

# Reading the git status
FILES=$(git.status)

for FILE in ${FILES[@]}; do
	FILE=${FILE#*  } # Trimming that leading "M  " status marker.

	if runes.isRune $FILE; then
		runes.log "Encrypting the \e[35m${lcWhite}${FILE}\e[0m file."
		runes.encrypt $FILE
		git.add $FILE
		runes.decrypt $FILE
	fi;
done

runes.encrypt.finish;
