#!/bin/sh

echo "runes"

# Reading the runes files
readarray RUNES < .runes

# Checks if the given path belongs to the runes file.
function isRune {
	for RUNE in ${RUNES[@]}; do
		if [[ $RUNE == $1 ]]; then
			return 0
		fi
	done

	return 255
}

IFS=$'\0'
FILES=$(git status --porcelain)

for FILE in ${FILES[@]}; do
	echo "Checking the files ${FILE}"
	if isRune $FILE; then
		echo "Found a rune ${FILE}"
		#TODO: encrypt
	fi;
done
