#!/bin/bash

source creep/runes/runes.sh
source creep/creep.sh

log=runes.log

# Reading the runes files
readarray RUNES < .creep/.runess

# Reading the git status
FILES=$(git.status)

for FILE in ${FILES[@]}; do
	FILE=${FILE#*  } # Trimming that leading "M  " status marker.

	if runes.isRune $FILE; then
		runes.log "Encrypting the \e[35m\e[7m${FILE}\e[0m file."
		runes.encrypt $FILE
		#TODO: encrypt
	fi;
done
